//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeCompanyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> TransportID { get; set; }
        public Nullable<int> BillAmount { get; set; }
        public string BillStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ClientName { get; set; }
        public string TransportName { get; set; }
    }
}
