//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeCompanyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryTime { get; set; }
        public Nullable<System.DateTime> RequestedDeliveryTime { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ClientName { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> TransportID { get; set; }
        public string TransportName { get; set; }
    }
}
