//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeCompanyPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int TransportID { get; set; }
        public string TransportType { get; set; }
        public Nullable<int> QuantityAllowed { get; set; }
    }
}
